# Generated by Django 5.2 on 2025-04-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_account", "0002_user_full_name_user_otp_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(
                default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
