# Generated by Django 5.2 on 2025-04-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_account", "0003_alter_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
