# Generated by Django 5.2 on 2025-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_account", "0004_alter_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
